### ISSUE TITLE
Cant select Character

### ISSUE THREAD

**Issue by Sifter959** [npcore-framework/npcore-server#5]
Maybe this will help you guys and gals. I am not a coder so I dont know if it will. This is just the errors I'm getting. I can create character but I cant spawn.
![ingame bug](https://user-images.githubusercontent.com/18460089/123503190-01ef8b80-d617-11eb-9400-f3b1a58600c6.png)
![console bug](https://user-images.githubusercontent.com/18460089/123503193-04ea7c00-d617-11eb-97d4-77b078037705.png)

**Comment by Savage912-Official** [comment]
Did you click on the character then click spawn?

**Comment by npcore-framework** [comment]
Please let us know if what @Savage912-Official suggested works.

**Comment by Sifter959** [comment]
Yes, I can click anywhere on the screen and no character is selected.

**Comment by MrAlfredd** [comment]
It has to do with your aspect ratio, try change it to 16:9.

**Comment by npcore-framework** [comment]
> Yes, I can click anywhere on the screen and no character is selected.

Right, the way character creation works is you gotta select the transparent ped model then the "Create Button" which should bring the clothing menu up afterwards.

If you continue to have this issue, feel free to hop on our Discord for some 1 to 1 support.

**Comment by Sifter959** [comment]
not the aspect ratio. and I understand how its suppose to work. my issue is that it wont let me select the transparent model. the initial screen where you can select male, female, dob, works. The transparent model is created. when i try to select the model, nothing happens.

**Comment by Sifter959** [comment]
this issue can be closed. for some reason it does not work on my desktop but it does on my laptop. thanks.

**Comment by npcore-framework** [comment]
> 
> 
> this issue can be closed. for some reason it does not work on my desktop but it does on my laptop. thanks.

Odd, what an intriguing issue lol. Thanks for the report by all means!

**Comment by MrAlfredd** [comment]
It sure has something to do with the aspect ratio and how ScreenRelToWorld function fetch where your mouse is hovering. I have the same problem since I'm also using an ultra wide screen. And when I changed to 16:9 it works, but not when I have 21:9
